#+TITLE: Software Release Guide (CWI CI Group)
#+AUTHOR: Jan-Willem Buurlage, Allard Hendriksen

* Introduction
This document consists of two parts. In the first part, we suggest useful tools,
a good project structure, and some further guidelines, for sharing your software
projects. In some sense, it is a checklist for your software package to make
sure that it is easy to use for others, yet allows you to keep the freedom to
develop your software further. The second part, /selected topics/, is a how-to
guide for common tasks that you may need to perform while working on software.

These notes are not intended to teach you the basics of programming, source
control, or for example using Linux. Instead, it is about everything you need
/after/ you become a capable programmer, when you start producing software that
becomes useful for others.

One question we should answer before diving in deep, is /why?/ Indeed, why
should we put so much effort in our software. We are, after all, scientists --
not software developers! We believe there are many reasons why we /should/ take
care in sharing our scientific software, some of them we list below.

- *Collaborations within the group*. Although everyone in the CI CWI group are
  individual researchers, our work has a lot in common. Most of us work on
  algorithms, target the same kind of data set, and often face the same
  problems. For example, more often than not, an issue that you are facing has
  already been tackled by someone before. Sharing our solutions means not having
  to reinvent the wheel. Furthermore, someone else their expertise may push your
  research further. Whether this means a new application of a neural network
  structure, combining algorithms together for even better reconstructions, or
  simply using a method you developed for the reconstruction of data recorded in
  our lab.
- *Collaborations with other groups.* The CI CWI group takes a unique position
  in research -- somewhere in between the hardcore mathematics, and the more
  experimental side of imaging. With our software, we can help bridge the gap
  between experimentalists (who are often still using what we consider ancient
  methods), and algorithm developers (who can be out of touch with the demands
  and requirements of real-world imaging experiments), by working together with
  both sides of this spectrum.
- *Publicity*. Putting out software that is being used by others gives a lot of
  exposure to yourself as a researcher, and the group as a whole. For example,
  ASTRA has been an important part of our public identity.
- *Real-world impact of your research.* Unfortunately, writing a beautiful
  article outlining all the ins and outs of your method does not mean that it
  will also be picked up and used by others. Time is scarce for everyone in
  science, and anything beyond the most trivial algorithm will most likely not
  be reimplemented outside our own research group. Publishing software alongside
  an article makes it /much/ easier for others to use and apply your methods.
- *Scientific output.* Slowly but surely, software itself is being recognized as
  scientific output. There are many journals and conferences dedicated to
  scientific software.

It can be intimidating to share your software with colleagues, let alone to
release it to the public. We always want to /*clean up the code, and fix this
last thing*/ before we share it. However, especially since very few of us (if
any) are trained as software engineers, it is not always clear what it means to
develop good, or /clean/, software. This means that a lot of software is kept
private until it is done, and regrettably this often means it is kept private
indefinitely.

Hopefully, after reading the next section, you will be fully equipped to turn
your software projects into clear, clean and usable packages. Our intention is
to ease the transition of your project from something that is written primarily
for yourself, to something others can also use.
* Anatomy of a software project
Let us assume that you have developed an image reconstruction algorithm. You
have designed your numerical experiments, and implemented them in Python
(perhaps on top of the ASTRA toolbox).

In the most extreme case, the result is a single script. This script contains
for example some classes, functions and some code that applies them to a data
set.

Here, we will transform this script into a software package that is installable
and usable by others, and maintainable and testable by you, the developer. We
will take the following steps, which we will explain in detail later. (1)
*Update project structure*. A software project consists of more than just the
code. In should also include additional files, containing additional information
for the user. (2) *Add documentation*. Since you developed the software, you
know exactly how it works (and how it doesn't). Unfortunately, your users cannot
read your mind. Minimally, you should provide some basic information on how to
install and use your software, as well as what your users are allowed to do with
it. (3) *Add files for distribution*. Before you can release your software into
the wild, you need to add build files, and license. (4) *Release the software*.
With a good structure, documentation and distribution files in place -- we are
ready for release. We add release notes to the project, and assign a version to
the software. (5) *Further development*. Unfortunately, having users also means
having some responsibility. Luckily, with the setup we recommend, you can
continue developing your software without frustrating your users by following a
small set of rules.

We will first discuss the steps, and it is not written to /following along as
you read/, but rather to give an overview of what a minimal software package
consists of. After this initial discussion, we will provide you with more detailed
information on how to realize these steps for your software, as most of the
steps can be automated.

** Update project structure
First, we need to convert our code into a clean and predictable structure. The
recommended structure depends mainly on the programming language used. We only
consider Python software for now, but we will discuss other languages later. Our
hypothetical software package will be called =hsp=, for hypothetical software
package.

We will first set up our directory as follows:
#+BEGIN_SRC bash
├── example
│   └── run_on_data.py
└── hsp
    ├── hsp.py
    └── __init__.py
#+END_SRC

Here, =hsp.py= contains functions and classes, while =run_on_data.py= contains
code applying them to data. Note in bigger projects you can split =hsp.py=
further into multiple files, grouping them together by functionality. The file
=__init__.py= ties them together. There can also be multiple examples.

With this structure, we can use =import hsp= from scripts residing at our root
folder. Later we will set our package up so that you can run this import
statement from anywhere.
** Add documentation
There are two classes of documentation. First, there is usually a readme file
called =README.md=, containing some basic information on the project. Second, detailed
documentation is provided on a separate webpage (hosted online or shipped
alongside the software). We will discuss a good way to set up initial
documentation.

The readme file is comparable to the metadata and abstract of an article. It
should provide a potential user with all the information they need to decide
whether to use your software. Like writing good abstracts, writing good readme
documents is an art form. At the minimum, it should contain the following. (1)
The name of your software package, together with a short (one or two sentences)
summary of what it does. (2) Information on how to install the software. If it
is a software library, it is usually a good idea to show a short example of code
written on top of the library. (3) Information on the authors, the license, how
to contribute, and potentially what article to cite if people use your software.

The more detailed documentation can contain the README as a landing page, but
typically takes a more /tutorial-like/ approach to describe the software.
Usually, this means explaining how to do some example task with the software, or
explaining the example code that is shipped alongside the library. The example
code itself can also be considered documentation, and can usually be a stripped
down version of the code you use yourself for e.g. numerical experiments.
Furthermore, the documentation should provide an API overview, documenting all
the classes and functions you expose to the user. This overview can be generated
automatically from your code, using function signatures and optional
/docstrings/ that you may have written. For Python projects, we recommend using
Sphinx to generate the documentation.
** Add files for distribution
Next, you should allow yourself and your users to use your package by a simple
=import= statement. For this, you can include a =setup.py= for =setuptools=,
allowing your users to do a =pip install=. You can also add support for =conda=
by including some basic =.yaml= files.

You should to include a =LICENSE.md= file letting our users know what they are
allowed to do with our software. Typically, software written by our group is
released under the GPL.
** Release the software
Releasing your software does not only mean that it is made available publicly.
It means to provide a fixed, frozen version of the code that has no known bugs,
and to assign it a version number. An initial version number can be =v0.0.1=.

This is an important service to your potential users, because it gives them a
predictable state of your code to fall back on. If you decide to further develop
your code, you can do this freely without worrying about breaking your users'
codes, because they can depend on this fixed release.

This brings us to another important file, the release notes, which are contained
in a file =CHANGELOG.md=. For the initial release, this file does not much
information. Maybe a notice that it is the first public release, and the date at
which it is published. However, as you add, amend, and change your software, you
may want to release a next version, say =v0.0.2=. In the release notes, you can
let the user know what has changed, and they should be able to see immediately
if they should expect any difficulties when upgrading to the new version.

We recommend using GitHub to publish your software. GitHub has a good mechanism
for managing releases. Simply click on the /releases/ button, and create a new
release. Provide a tag, name, and some basic information -- and GitHub will
automatically mark the current state of the software as a new release. Next, if
it is a Python project, you can upload the new release to Anaconda and/or PyPI.
** Further development
Now that your software is out in the public, making big changes to your software
probably means breaking your users code. As a courtesy to your users, whenever
you add, change or remove something add a line to your change log describing
what is new.

When releasing your new software, choose a new version number according to
semantic versioning. In brief, when choosing a new number =vX.Y.Z= increment =Z=
if you are fixing incorrect behaviour, =Y= if you are adding new functionality
but user code should not break, and =X= if you make major changes that can break
user code. This gives your users a lot of information on the new release simply
by looking at the version number: they can always safely upgrade to your new
release if =X= is unchanged, and should check what's new when either =X= or =Y=
is increased.
** Putting theory to practice: developing a Python a software package
Instead of performing all the steps outlined above manually, the easiest way to
set up your project correctly is by using the =cookiecutter= template we
provide.

*** Set up software project structure
First, install =cookiecutter=.
#+BEGIN_SRC bash
pip install -U cookiecutter
#+END_SRC
We provide a basic template for Python software packages. You can use this
template to set up a new directory that contains all the files that were
discussed in the previous sections, as well as a mock software project. You can
then copy your code into the Python files that is generated by the template
(for details on how to do this, see below). First, run the following command,
and answer the questions that are asked.
#+BEGIN_SRC bash
cookiecutter https://github.com/cicwi/cookiecutter-cicwi.git
#+END_SRC
This will generate a directory with the name of your project. Next, you need to
set up a new GitHub repository. We assume you have made such a repository, and
that it resides at https://github.com/username/project, and that the name of
your project is =hsp=. Next we set up Git.
#+BEGIN_SRC bash
cd hsp # replace with project name
git init
git remote add github https://github.com/username/project
#+END_SRC
To use the template, we require the installation of some dependencies and tools.
We assume that you are inside a =conda= environment. You can install all the
dependencies by running the following command.
#+BEGIN_SRC bash
make install_dev install
#+END_SRC
*** Adding your code
Now that everything is set up, we are ready to copy your code into the project.
Typically, the code you want to share takes the form of a library. In
particular, there are some classes and functions that others can make use of.
Simply copy these classes and functions to =hsp/hsp.py=. This file contains the
code for your library.

It is a good idea to add a minimal example of how to use your library. This
should somehow represent the core functionality of the software and should not
be more than a couple of lines of code. For this, you can edit the file
=examples/getting_started.py=. Your application code, that for example applies
your library to data, can probably also be converted to an interesting example.
You can add more scripts to the =examples/= directory showing more advanced
usage of your library.
*** Releasing 
To release
1. Update documentation
   1. make docs
2. Commit code
3. Create release with bumpversion
   1. =bumpversion major=
   2. =bumpversion minor=
   3. =bumpversion patch=
4. Push to github
5. Create release on GitHub
6. Create GitHub pages documentation

After release
1. Maintain CHANGELOG

**** Make commands

The project comes with a default Makefile. The Makefile has a
reasonable number of built-in commands.

***** Development requirements
Download and install development requirements into your current conda
environment with
#+BEGIN_SRC bash
make install_dev
#+END_SRC

****** TODO this installs

***** Install requirements
Download and install your project requirements into your current conda
environment with
#+BEGIN_SRC bash
make install
#+END_SRC

****** TODO this installs

***** Update the documentation.
Update your documentation with
#+BEGIN_SRC bash
make docs
#+END_SRC
***** Code formatting
Automatically reformat the code of your project to a common format
with
#+BEGIN_SRC bash
make style
#+END_SRC
***** Build conda package
The command
#+BEGIN_SRC bash
make conda_package
#+END_SRC
builds a conda package, which you can share on https://anaconda.org/.
